# Downloading data

In [1]:
!git clone https://github.com/kevinwang09/pyProj
# !git pull https://github.com/kevinwang09/pyProj

Cloning into 'pyProj'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 17 (delta 4), reused 10 (delta 3), pack-reused 0
Unpacking objects: 100% (17/17), done.


In [2]:
!pwd
!ls

/content
pyProj	sample_data


# Loading data and libraries

In [3]:
# Import necessary modules
import numpy as np
import pandas as pd
import keras
from keras.layers import Dense
from keras.models import Sequential
from keras.utils import to_categorical
from sklearn.preprocessing import OneHotEncoder

In [4]:
penguins = pd.read_csv("pyProj/intro_keras/penguins.csv")
print(penguins.loc[range(5),:])
penguins.describe()

  species     island  bill_length_mm  ...  body_mass_g     sex  year
0  Adelie  Torgersen            39.1  ...       3750.0    male  2007
1  Adelie  Torgersen            39.5  ...       3800.0  female  2007
2  Adelie  Torgersen            40.3  ...       3250.0  female  2007
3  Adelie  Torgersen             NaN  ...          NaN     NaN  2007
4  Adelie  Torgersen            36.7  ...       3450.0  female  2007

[5 rows x 8 columns]


bill_length_mm  bill_depth_mm  ...  body_mass_g         year
count      342.000000     342.000000  ...   342.000000   344.000000
mean        43.921930      17.151170  ...  4201.754386  2008.029070
std          5.459584       1.974793  ...   801.954536     0.818356
min         32.100000      13.100000  ...  2700.000000  2007.000000
25%         39.225000      15.600000  ...  3550.000000  2007.000000
50%         44.450000      17.300000  ...  4050.000000  2008.000000
75%         48.500000      18.700000  ...  4750.000000  2009.000000
max         59.600000      21.500000  ...  6300.000000  2009.000000

[8 rows x 5 columns]

# Cleaning data into numpy arrays

In [5]:
penguins = penguins.dropna()

In [6]:
predictors = penguins.drop(["species"], axis = 1)
predictors = np.array(pd.get_dummies(data = predictors, columns = ["island", "sex"]))
# predictors = np.asarray(predictors).astype(np.float32)
print(predictors)
print(type(predictors))
predictors.shape

[[ 39.1  18.7 181.  ...   1.    0.    1. ]
 [ 39.5  17.4 186.  ...   1.    1.    0. ]
 [ 40.3  18.  195.  ...   1.    1.    0. ]
 ...
 [ 49.6  18.2 193.  ...   0.    0.    1. ]
 [ 50.8  19.  210.  ...   0.    0.    1. ]
 [ 50.2  18.7 198.  ...   0.    1.    0. ]]
<class 'numpy.ndarray'>


(333, 10)

In [24]:
predictors = np.array(predictors)
from sklearn.preprocessing import StandardScaler

predictors = StandardScaler().fit_transform(predictors)

In [25]:
target = np.array(pd.get_dummies(penguins["species"]))
# target = np.asarray(target).astype(np.float32)
print(target[range(5),:])
print(type(target))
print(target.shape)

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]
<class 'numpy.ndarray'>
(333, 3)


# Making Keras model


In [26]:
ncols = predictors.shape[1]
print(ncols)

10


In [27]:
model = Sequential()
model.add(Dense(100, activation = "relu", input_shape = (ncols, )))
model.add(Dense(100, activation = "relu"))
model.add(Dense(3, activation = "softmax"))
model.compile(optimizer = "sgd", loss = "categorical_crossentropy", metrics = ["accuracy"])
model.fit(predictors, target, epochs = 5 , validation_split = 0.3)

Epoch 1/5
8/8 [==============================] - 0s 20ms/step - loss: 1.2107 - accuracy: 0.1888 - val_loss: 1.1932 - val_accuracy: 0.2000
Epoch 2/5
8/8 [==============================] - 0s 4ms/step - loss: 1.0117 - accuracy: 0.4807 - val_loss: 1.2140 - val_accuracy: 0.3000
Epoch 3/5
8/8 [==============================] - 0s 4ms/step - loss: 0.8565 - accuracy: 0.7210 - val_loss: 1.2359 - val_accuracy: 0.3100
Epoch 4/5
8/8 [==============================] - 0s 4ms/step - loss: 0.7314 - accuracy: 0.8670 - val_loss: 1.2669 - val_accuracy: 0.3200
Epoch 5/5
8/8 [==============================] - 0s 5ms/step - loss: 0.6267 - accuracy: 0.9442 - val_loss: 1.2959 - val_accuracy: 0.3200


# Resubstitution error

In [28]:
predictions = model.predict(predictors)
print(predictions[[1, 100, 200, 300], :])

[[0.6846635  0.10050597 0.21483044]
 [0.5328056  0.18035178 0.28684255]
 [0.31071016 0.13628355 0.5530063 ]
 [0.4198847  0.24836278 0.33175248]]
